// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.cloudpubsub.protobuf;

public final class CustomerMessageOuterClass {
  private CustomerMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CustomerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string first_name = 1;</code>
     * @return Whether the firstName field is set.
     */
    boolean hasFirstName();
    /**
     * <code>required string first_name = 1;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>required string first_name = 1;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>required string last_name = 2;</code>
     * @return Whether the lastName field is set.
     */
    boolean hasLastName();
    /**
     * <code>required string last_name = 2;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>required string last_name = 2;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>optional string country = 3;</code>
     * @return Whether the country field is set.
     */
    boolean hasCountry();
    /**
     * <code>optional string country = 3;</code>
     * @return The country.
     */
    java.lang.String getCountry();
    /**
     * <code>optional string country = 3;</code>
     * @return The bytes for country.
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>optional int32 age = 4;</code>
     * @return Whether the age field is set.
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 4;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code CustomerMessage}
   */
  public static final class CustomerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CustomerMessage)
      CustomerMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomerMessage.newBuilder() to construct.
    private CustomerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomerMessage() {
      firstName_ = "";
      lastName_ = "";
      country_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CustomerMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CustomerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              firstName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              lastName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              country_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudpubsub.protobuf.CustomerMessageOuterClass.internal_static_CustomerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudpubsub.protobuf.CustomerMessageOuterClass.internal_static_CustomerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage.class, com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage.Builder.class);
    }

    private int bitField0_;
    public static final int FIRST_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstName_;
    /**
     * <code>required string first_name = 1;</code>
     * @return Whether the firstName field is set.
     */
    @java.lang.Override
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string first_name = 1;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string first_name = 1;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastName_;
    /**
     * <code>required string last_name = 2;</code>
     * @return Whether the lastName field is set.
     */
    @java.lang.Override
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string last_name = 2;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string last_name = 2;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 3;
    private volatile java.lang.Object country_;
    /**
     * <code>optional string country = 3;</code>
     * @return Whether the country field is set.
     */
    @java.lang.Override
    public boolean hasCountry() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string country = 3;</code>
     * @return The country.
     */
    @java.lang.Override
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          country_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string country = 3;</code>
     * @return The bytes for country.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 4;
    private int age_;
    /**
     * <code>optional int32 age = 4;</code>
     * @return Whether the age field is set.
     */
    @java.lang.Override
    public boolean hasAge() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 age = 4;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFirstName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, country_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, age_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, country_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage)) {
        return super.equals(obj);
      }
      com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage other = (com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage) obj;

      if (hasFirstName() != other.hasFirstName()) return false;
      if (hasFirstName()) {
        if (!getFirstName()
            .equals(other.getFirstName())) return false;
      }
      if (hasLastName() != other.hasLastName()) return false;
      if (hasLastName()) {
        if (!getLastName()
            .equals(other.getLastName())) return false;
      }
      if (hasCountry() != other.hasCountry()) return false;
      if (hasCountry()) {
        if (!getCountry()
            .equals(other.getCountry())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFirstName()) {
        hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getFirstName().hashCode();
      }
      if (hasLastName()) {
        hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getLastName().hashCode();
      }
      if (hasCountry()) {
        hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
        hash = (53 * hash) + getCountry().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CustomerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CustomerMessage)
        com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudpubsub.protobuf.CustomerMessageOuterClass.internal_static_CustomerMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudpubsub.protobuf.CustomerMessageOuterClass.internal_static_CustomerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage.class, com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage.Builder.class);
      }

      // Construct using com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        firstName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lastName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        country_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudpubsub.protobuf.CustomerMessageOuterClass.internal_static_CustomerMessage_descriptor;
      }

      @java.lang.Override
      public com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage getDefaultInstanceForType() {
        return com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage build() {
        com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage buildPartial() {
        com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage result = new com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.firstName_ = firstName_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lastName_ = lastName_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.country_ = country_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage) {
          return mergeFrom((com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage other) {
        if (other == com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage.getDefaultInstance()) return this;
        if (other.hasFirstName()) {
          bitField0_ |= 0x00000001;
          firstName_ = other.firstName_;
          onChanged();
        }
        if (other.hasLastName()) {
          bitField0_ |= 0x00000002;
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.hasCountry()) {
          bitField0_ |= 0x00000004;
          country_ = other.country_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFirstName()) {
          return false;
        }
        if (!hasLastName()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object firstName_ = "";
      /**
       * <code>required string first_name = 1;</code>
       * @return Whether the firstName field is set.
       */
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string first_name = 1;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            firstName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string first_name = 1;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string first_name = 1;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string first_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>required string first_name = 1;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>required string last_name = 2;</code>
       * @return Whether the lastName field is set.
       */
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string last_name = 2;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string last_name = 2;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string last_name = 2;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string last_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>required string last_name = 2;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>optional string country = 3;</code>
       * @return Whether the country field is set.
       */
      public boolean hasCountry() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string country = 3;</code>
       * @return The country.
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            country_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string country = 3;</code>
       * @return The bytes for country.
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string country = 3;</code>
       * @param value The country to set.
       * @return This builder for chaining.
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountry() {
        bitField0_ = (bitField0_ & ~0x00000004);
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 3;</code>
       * @param value The bytes for country to set.
       * @return This builder for chaining.
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        country_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 4;</code>
       * @return Whether the age field is set.
       */
      @java.lang.Override
      public boolean hasAge() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 age = 4;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 4;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000008;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000008);
        age_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CustomerMessage)
    }

    // @@protoc_insertion_point(class_scope:CustomerMessage)
    private static final com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage();
    }

    public static com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CustomerMessage>
        PARSER = new com.google.protobuf.AbstractParser<CustomerMessage>() {
      @java.lang.Override
      public CustomerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomerMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomerMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomerMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cloudpubsub.protobuf.CustomerMessageOuterClass.CustomerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\"V\n\017CustomerMessage\022\022\n\nf" +
      "irst_name\030\001 \002(\t\022\021\n\tlast_name\030\002 \002(\t\022\017\n\007co" +
      "untry\030\003 \001(\t\022\013\n\003age\030\004 \001(\005B5\n\030com.cloudpub" +
      "sub.protobufB\031CustomerMessageOuterClass"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CustomerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CustomerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerMessage_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Country", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
